
export const SCHEDULE_206_TEMPLATE = [
  {"day": 1, "period": 1, "course": "體育", "teacher": "呂育真", "startTime": "08:10", "endTime": "09:00"},
  {"day": 1, "period": 2, "course": "物質構造與性質", "teacher": "李亦晴", "startTime": "09:10", "endTime": "10:00"},
  {"day": 1, "period": 3, "course": "班會", "teacher": "蘇曉君", "startTime": "10:10", "endTime": "11:00"},
  {"day": 1, "period": 4, "course": "團體活動", "teacher": "蘇曉君", "startTime": "11:10", "endTime": "12:00"},
  {"day": 1, "period": 5, "course": "力學二與熱", "teacher": "黃貫倫", "startTime": "13:00", "endTime": "13:50"},
  {"day": 1, "period": 6, "course": "國文", "teacher": "蘇曉君", "startTime": "14:10", "endTime": "15:00"},
  {"day": 1, "period": 7, "course": "數學A", "teacher": "蘇曉洳", "startTime": "15:10", "endTime": "16:00"},
  {"day": 1, "period": 8, "course": "數學(輔)", "teacher": "蘇曉洳", "startTime": "16:10", "endTime": "17:00"},
  {"day": 2, "period": 1, "course": "國文", "teacher": "蘇曉君", "startTime": "08:10", "endTime": "09:00"},
  {"day": 2, "period": 2, "course": "數學A", "teacher": "蘇曉洳", "startTime": "09:10", "endTime": "10:00"},
  {"day": 2, "period": 3, "course": "力學二與熱", "teacher": "黃貫倫", "startTime": "10:10", "endTime": "11:00"},
  {"day": 2, "period": 4, "course": "團體活動", "teacher": "蘇曉君", "startTime": "11:10", "endTime": "12:00"},
  {"day": 2, "period": 5, "course": "體育", "teacher": "呂育真", "startTime": "13:00", "endTime": "13:50"},
  {"day": 2, "period": 6, "course": "地理", "teacher": "陳怡帆", "startTime": "14:10", "endTime": "15:00"},
  {"day": 2, "period": 7, "course": "英文", "teacher": "謝富展", "startTime": "15:10", "endTime": "16:00"},
  {"day": 3, "period": 1, "course": "數學A", "teacher": "蘇曉洳", "startTime": "08:10", "endTime": "09:00"},
  {"day": 3, "period": 2, "course": "國文", "teacher": "蘇曉君", "startTime": "09:10", "endTime": "10:00"},
  {"day": 3, "period": 3, "course": "化學-探究B", "teacher": "李亦晴 / 林易辰", "startTime": "10:10", "endTime": "11:00"},
  {"day": 3, "period": 4, "course": "化學-探究B", "teacher": "李亦晴 / 林易辰", "startTime": "11:10", "endTime": "12:00"},
  {"day": 3, "period": 5, "course": "英文", "teacher": "謝富展", "startTime": "13:00", "endTime": "13:50"},
  {"day": 3, "period": 6, "course": "生活科技", "teacher": "周致羽", "startTime": "14:10", "endTime": "15:00"},
  {"day": 3, "period": 7, "course": "生活科技", "teacher": "周致羽", "startTime": "15:10", "endTime": "16:00"},
  {"day": 4, "period": 1, "course": "國文", "teacher": "蘇曉君", "startTime": "08:10", "endTime": "09:00"},
  {"day": 4, "period": 2, "course": "英文", "teacher": "謝富展", "startTime": "09:10", "endTime": "10:00"},
  {"day": 4, "period": 3, "course": "彈性課程", "teacher": "蘇曉君", "startTime": "10:10", "endTime": "11:00"},
  {"day": 4, "period": 4, "course": "彈性課程", "teacher": "蘇曉君", "startTime": "11:10", "endTime": "12:00"},
  {"day": 4, "period": 5, "course": "物質構造與性質", "teacher": "李亦晴", "startTime": "13:00", "endTime": "13:50"},
  {"day": 4, "period": 6, "course": "數學A", "teacher": "蘇曉洳", "startTime": "14:10", "endTime": "15:00"},
  {"day": 4, "period": 7, "course": "音樂", "teacher": "吳明瑾", "startTime": "15:10", "endTime": "16:00"},
  {"day": 5, "period": 1, "course": "地理", "teacher": "陳怡帆", "startTime": "08:10", "endTime": "09:00"},
  {"day": 5, "period": 2, "course": "英文", "teacher": "謝富展", "startTime": "09:10", "endTime": "10:00"},
  {"day": 5, "period": 3, "course": "多元選修", "teacher": "選修老師", "startTime": "10:10", "endTime": "11:00"},
  {"day": 5, "period": 4, "course": "多元選修", "teacher": "選修老師", "startTime": "11:10", "endTime": "12:00"},
  {"day": 5, "period": 5, "course": "音樂", "teacher": "吳明瑾", "startTime": "13:00", "endTime": "13:50"},
  {"day": 5, "period": 6, "course": "跨班課程", "teacher": "跨班老師", "startTime": "14:10", "endTime": "15:00"},
  {"day": 5, "period": 7, "course": "跨班課程", "teacher": "跨班老師", "startTime": "15:10", "endTime": "16:00"}
];
